version: '3.4'

services:
  demo.opentracing:
    volumes:
      - C:\Users\hp\onecoremsvsmon:C:\remote_debugger:ro
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /fallbackloadremotemanagedpdbs /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_demo.opentracing$ Demo.OpenTracing.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

  demo.webapi:
    volumes:
      - C:\Users\hp\onecoremsvsmon:C:\remote_debugger:ro
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /fallbackloadremotemanagedpdbs /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_demo.webapi$ Demo.WebApi.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"


  demo.zipkinweb:
    volumes:
      - C:\Users\hp\onecoremsvsmon:C:\remote_debugger:ro
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /fallbackloadremotemanagedpdbs /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_demo.zipkinweb$ Demo.ZipKinWeb.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"


  demo.zipkinweb2:
    volumes:
      - C:\Users\hp\onecoremsvsmon:C:\remote_debugger:ro
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /fallbackloadremotemanagedpdbs /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_demo.zipkinweb2$ Demo.ZipKinWeb2.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

